// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//     
//	   Copyright (c) 2017 Citrix ShareFile. All rights reserved.
// </auto-generated>
// ------------------------------------------------------------------------------

package com.citrix.sharefile.api.entities;

import com.citrix.sharefile.api.SFApiQuery;
import com.citrix.sharefile.api.interfaces.ISFApiClient;
import com.citrix.sharefile.api.interfaces.ISFQuery;
import com.citrix.sharefile.api.models.SFGenericConfig;
import com.citrix.sharefile.api.models.SFODataFeed;

public class SFConfigsEntity extends SFEntitiesBase {
    public SFConfigsEntity(ISFApiClient client) {
        super(client);
    }

    /**
     * Get Configs
     *
     * @return List of GenericConfg
     */
    public ISFQuery<SFODataFeed<SFGenericConfig>> get() {

        SFApiQuery<SFODataFeed<SFGenericConfig>> sfApiQuery = new SFApiQuery<SFODataFeed<SFGenericConfig>>(this.client);
        sfApiQuery.setFrom("Configs");
        sfApiQuery.setHttpMethod("GET");
        return sfApiQuery;
    }

}

