// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//     
//	   Copyright (c) 2017 Citrix ShareFile. All rights reserved.
// </auto-generated>
// ------------------------------------------------------------------------------

package com.citrix.sharefile.api.models;

import com.google.gson.annotations.SerializedName;

public class SFAccessControlFailedEntry extends SFODataObject {

    @SerializedName("AccessControl")
    private SFAccessControl AccessControl;
    @SerializedName("Code")
    private String Code;
    @SerializedName("Message")
    private SFODataExceptionMessage Message;

    /**
     * Entity
     */
    public SFAccessControl getAccessControl() {
        return this.AccessControl;
    }

    /**
     * Entity
     */
    public void setAccessControl(SFAccessControl accesscontrol) {
        this.AccessControl = accesscontrol;
    }

    /**
     * Failure code
     */
    public String getCode() {
        return this.Code;
    }

    /**
     * Failure code
     */
    public void setCode(String code) {
        this.Code = code;
    }

    /**
     * Exception message
     */
    public SFODataExceptionMessage getMessage() {
        return this.Message;
    }

    /**
     * Exception message
     */
    public void setMessage(SFODataExceptionMessage message) {
        this.Message = message;
    }

}