// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//     
//	   Copyright (c) 2017 Citrix ShareFile. All rights reserved.
// </auto-generated>
// ------------------------------------------------------------------------------

package com.citrix.sharefile.api.models;

import com.google.gson.annotations.SerializedName;

public class SFAccountItemStatusProvider extends SFODataObject {

    @SerializedName("Active")
    private Boolean Active;

    /**
     * True if the current ShareFile account is enabled to use the specific
     */
    public Boolean getActive() {
        return this.Active;
    }

    /**
     * True if the current ShareFile account is enabled to use the specific
     */
    public void setActive(Boolean active) {
        this.Active = active;
    }

}