// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//     
//	   Copyright (c) 2017 Citrix ShareFile. All rights reserved.
// </auto-generated>
// ------------------------------------------------------------------------------

package com.citrix.sharefile.api.models;

import com.google.gson.annotations.SerializedName;

public class SFAccountZoneUsage extends SFODataObject {

    @SerializedName("TotalFileSizeBytes")
    private Long TotalFileSizeBytes;
    @SerializedName("Zone")
    private SFZone Zone;
    @SerializedName("RootFolderCount")
    private Long RootFolderCount;
    @SerializedName("FileCount")
    private Long FileCount;

    public Long getTotalFileSizeBytes() {
        return this.TotalFileSizeBytes;
    }

    public void setTotalFileSizeBytes(Long totalfilesizebytes) {
        this.TotalFileSizeBytes = totalfilesizebytes;
    }

    public SFZone getZone() {
        return this.Zone;
    }

    public void setZone(SFZone zone) {
        this.Zone = zone;
    }

    public Long getRootFolderCount() {
        return this.RootFolderCount;
    }

    public void setRootFolderCount(Long rootfoldercount) {
        this.RootFolderCount = rootfoldercount;
    }

    public Long getFileCount() {
        return this.FileCount;
    }

    public void setFileCount(Long filecount) {
        this.FileCount = filecount;
    }

}