// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//     
//	   Copyright (c) 2017 Citrix ShareFile. All rights reserved.
// </auto-generated>
// ------------------------------------------------------------------------------

package com.citrix.sharefile.api.models;

import com.google.gson.annotations.SerializedName;

public class SFAzureSBTopicsResponse extends SFODataObject {

    @SerializedName("Success")
    private String Success;

    public String getSuccess() {
        return this.Success;
    }

    public void setSuccess(String success) {
        this.Success = success;
    }

}