// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//     
//	   Copyright (c) 2017 Citrix ShareFile. All rights reserved.
// </auto-generated>
// ------------------------------------------------------------------------------

package com.citrix.sharefile.api.models;

import com.citrix.sharefile.api.enumerations.SFSafeEnum;
import com.google.gson.annotations.SerializedName;

public class SFBundle extends SFODataObject {

    @SerializedName("BundleType")
    private SFSafeEnum<SFBundleType> BundleType;

    public SFSafeEnum<SFBundleType> getBundleType() {
        return this.BundleType;
    }

    public void setBundleType(SFSafeEnum<SFBundleType> bundletype) {
        this.BundleType = bundletype;
    }

}