// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//     
//	   Copyright (c) 2017 Citrix ShareFile. All rights reserved.
// </auto-generated>
// ------------------------------------------------------------------------------

package com.citrix.sharefile.api.models;

import com.google.gson.annotations.SerializedName;

import java.util.ArrayList;

public class SFDocumentViewEvent extends SFODataObject {

    @SerializedName("AccountId")
    private String AccountId;
    @SerializedName("Data")
    private ArrayList<SFDocumentViewPageData> Data;

    /**
     * Id of the account viewing the document
     */
    public String getAccountId() {
        return this.AccountId;
    }

    /**
     * Id of the account viewing the document
     */
    public void setAccountId(String accountid) {
        this.AccountId = accountid;
    }

    /**
     * Data associated with the document view event
     */
    public ArrayList<SFDocumentViewPageData> getData() {
        return this.Data;
    }

    /**
     * Data associated with the document view event
     */
    public void setData(ArrayList<SFDocumentViewPageData> data) {
        this.Data = data;
    }

}