// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//     
//	   Copyright (c) 2017 Citrix ShareFile. All rights reserved.
// </auto-generated>
// ------------------------------------------------------------------------------

package com.citrix.sharefile.api.models;

import com.google.gson.annotations.SerializedName;

public class SFEditingProhibitedDefaultSetting extends SFODataObject {

    @SerializedName("HasDefaultValue")
    private Boolean HasDefaultValue;
    @SerializedName("ShouldPreventUserChanges")
    private Boolean ShouldPreventUserChanges;

    public Boolean getHasDefaultValue() {
        return this.HasDefaultValue;
    }

    public void setHasDefaultValue(Boolean hasdefaultvalue) {
        this.HasDefaultValue = hasdefaultvalue;
    }

    public Boolean getShouldPreventUserChanges() {
        return this.ShouldPreventUserChanges;
    }

    public void setShouldPreventUserChanges(Boolean shouldpreventuserchanges) {
        this.ShouldPreventUserChanges = shouldpreventuserchanges;
    }

}