// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//     
//	   Copyright (c) 2017 Citrix ShareFile. All rights reserved.
// </auto-generated>
// ------------------------------------------------------------------------------

package com.citrix.sharefile.api.models;

import com.citrix.sharefile.api.enumerations.SFSafeEnum;
import com.google.gson.annotations.SerializedName;

public class SFEditingPlatformInfo extends SFODataObject {

    @SerializedName("EditingPlatform")
    private SFSafeEnum<SFEditingPlatform> EditingPlatform;
    @SerializedName("ItemProtocolLink")
    private SFItemProtocolLink ItemProtocolLink;

    public SFSafeEnum<SFEditingPlatform> getEditingPlatform() {
        return this.EditingPlatform;
    }

    public void setEditingPlatform(SFSafeEnum<SFEditingPlatform> editingplatform) {
        this.EditingPlatform = editingplatform;
    }

    public SFItemProtocolLink getItemProtocolLink() {
        return this.ItemProtocolLink;
    }

    public void setItemProtocolLink(SFItemProtocolLink itemprotocollink) {
        this.ItemProtocolLink = itemprotocollink;
    }

}