// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//     
//	   Copyright (c) 2017 Citrix ShareFile. All rights reserved.
// </auto-generated>
// ------------------------------------------------------------------------------

package com.citrix.sharefile.api.models;

import com.google.gson.annotations.SerializedName;

public class SFEncryptedEmailCreateParams extends SFEncryptedEmailReplyParams {

    @SerializedName("RequireUserInfo")
    private Boolean RequireUserInfo;
    @SerializedName("RequireLogin")
    private Boolean RequireLogin;

    public Boolean getRequireUserInfo() {
        return this.RequireUserInfo;
    }

    public void setRequireUserInfo(Boolean requireuserinfo) {
        this.RequireUserInfo = requireuserinfo;
    }

    public Boolean getRequireLogin() {
        return this.RequireLogin;
    }

    public void setRequireLogin(Boolean requirelogin) {
        this.RequireLogin = requirelogin;
    }

}