// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//     
//	   Copyright (c) 2017 Citrix ShareFile. All rights reserved.
// </auto-generated>
// ------------------------------------------------------------------------------

package com.citrix.sharefile.api.models;

import com.google.gson.annotations.SerializedName;

public class SFFileAndFolderPolicy extends SFPolicy {

    @SerializedName("Settings")
    private SFFileAndFolderSettings Settings;

    /**
     * The settings managed for this Policy
     */
    public SFFileAndFolderSettings getSettings() {
        return this.Settings;
    }

    /**
     * The settings managed for this Policy
     */
    public void setSettings(SFFileAndFolderSettings settings) {
        this.Settings = settings;
    }

}