// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//     
//	   Copyright (c) 2017 Citrix ShareFile. All rights reserved.
// </auto-generated>
// ------------------------------------------------------------------------------

package com.citrix.sharefile.api.models;

import com.google.gson.annotations.SerializedName;

import java.util.ArrayList;

public class SFForbiddenOAuthClientNameWords extends SFODataObject {

    @SerializedName("Words")
    private ArrayList<String> Words;

    public ArrayList<String> getWords() {
        return this.Words;
    }

    public void setWords(ArrayList<String> words) {
        this.Words = words;
    }

}