// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//     
//	   Copyright (c) 2017 Citrix ShareFile. All rights reserved.
// </auto-generated>
// ------------------------------------------------------------------------------

package com.citrix.sharefile.api.models;

import com.citrix.sharefile.api.enumerations.SFSafeEnum;
import com.google.gson.annotations.SerializedName;

public class SFItemDlpInfo extends SFODataObject {

    @SerializedName("Status")
    private SFSafeEnum<SFDlpStatus> Status;

    /**
     * File scan status
     */
    public SFSafeEnum<SFDlpStatus> getStatus() {
        return this.Status;
    }

    /**
     * File scan status
     */
    public void setStatus(SFSafeEnum<SFDlpStatus> status) {
        this.Status = status;
    }

}