// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//     
//	   Copyright (c) 2017 Citrix ShareFile. All rights reserved.
// </auto-generated>
// ------------------------------------------------------------------------------

package com.citrix.sharefile.api.models;

import com.google.gson.annotations.SerializedName;

import java.util.ArrayList;

public class SFNotifyUsersParams extends SFODataObject {

    @SerializedName("UserIds")
    private ArrayList<String> UserIds;
    @SerializedName("CustomMessage")
    private String CustomMessage;

    public ArrayList<String> getUserIds() {
        return this.UserIds;
    }

    public void setUserIds(ArrayList<String> userids) {
        this.UserIds = userids;
    }

    public String getCustomMessage() {
        return this.CustomMessage;
    }

    public void setCustomMessage(String custommessage) {
        this.CustomMessage = custommessage;
    }

}