// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//     
//	   Copyright (c) 2017 Citrix ShareFile. All rights reserved.
// </auto-generated>
// ------------------------------------------------------------------------------

package com.citrix.sharefile.api.models;

import com.citrix.sharefile.api.enumerations.SFSafeEnum;
import com.google.gson.annotations.SerializedName;

import java.util.ArrayList;

public class SFPlanAddonUser extends SFODataObject {

    @SerializedName("User")
    private SFUser User;
    @SerializedName("SpecialUserRole")
    private ArrayList<SFSafeEnum<SFMobileUserRole>> SpecialUserRole;

    public SFUser getUser() {
        return this.User;
    }

    public void setUser(SFUser user) {
        this.User = user;
    }

    public ArrayList<SFSafeEnum<SFMobileUserRole>> getSpecialUserRole() {
        return this.SpecialUserRole;
    }

    public void setSpecialUserRole(ArrayList<SFSafeEnum<SFMobileUserRole>> specialuserrole) {
        this.SpecialUserRole = specialuserrole;
    }

}