// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//     
//	   Copyright (c) 2017 Citrix ShareFile. All rights reserved.
// </auto-generated>
// ------------------------------------------------------------------------------

package com.citrix.sharefile.api.models;

import com.citrix.sharefile.api.enumerations.SFSafeEnum;
import com.google.gson.annotations.SerializedName;

public class SFPreviewPlatformInfo extends SFODataObject {

    @SerializedName("PreviewPlatform")
    private SFSafeEnum<SFPreviewPlatform> PreviewPlatform;
    @SerializedName("ItemProtocolLink")
    private SFItemProtocolLink ItemProtocolLink;

    /**
     * Indicates the Preview platform
     */
    public SFSafeEnum<SFPreviewPlatform> getPreviewPlatform() {
        return this.PreviewPlatform;
    }

    /**
     * Indicates the Preview platform
     */
    public void setPreviewPlatform(SFSafeEnum<SFPreviewPlatform> previewplatform) {
        this.PreviewPlatform = previewplatform;
    }

    /**
     * Indicates the ItemProtocolLink for this Preview platform
     */
    public SFItemProtocolLink getItemProtocolLink() {
        return this.ItemProtocolLink;
    }

    /**
     * Indicates the ItemProtocolLink for this Preview platform
     */
    public void setItemProtocolLink(SFItemProtocolLink itemprotocollink) {
        this.ItemProtocolLink = itemprotocollink;
    }

}