// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//     
//	   Copyright (c) 2017 Citrix ShareFile. All rights reserved.
// </auto-generated>
// ------------------------------------------------------------------------------

package com.citrix.sharefile.api.models;

import com.google.gson.annotations.SerializedName;

public class SFResetPasswordRequest extends SFODataObject {

    @SerializedName("Token")
    private String Token;
    @SerializedName("Password")
    private String Password;
    @SerializedName("Subdomain")
    private String Subdomain;
    @SerializedName("Tool")
    private String Tool;

    public String getToken() {
        return this.Token;
    }

    public void setToken(String token) {
        this.Token = token;
    }

    public String getPassword() {
        return this.Password;
    }

    public void setPassword(String password) {
        this.Password = password;
    }

    public String getSubdomain() {
        return this.Subdomain;
    }

    public void setSubdomain(String subdomain) {
        this.Subdomain = subdomain;
    }

    public String getTool() {
        return this.Tool;
    }

    public void setTool(String tool) {
        this.Tool = tool;
    }

}