// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//     
//	   Copyright (c) 2017 Citrix ShareFile. All rights reserved.
// </auto-generated>
// ------------------------------------------------------------------------------

package com.citrix.sharefile.api.models;

import com.google.gson.annotations.SerializedName;

public class SFRequireWebPopResult extends SFODataObject {

    @SerializedName("RequireWebPop")
    private Boolean RequireWebPop;

    /**
     * Indicates if WebPop is required for authentication.
     */
    public Boolean getRequireWebPop() {
        return this.RequireWebPop;
    }

    /**
     * Indicates if WebPop is required for authentication.
     */
    public void setRequireWebPop(Boolean requirewebpop) {
        this.RequireWebPop = requirewebpop;
    }

}