// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//     
//	   Copyright (c) 2017 Citrix ShareFile. All rights reserved.
// </auto-generated>
// ------------------------------------------------------------------------------

package com.citrix.sharefile.api.models;

import com.google.gson.annotations.SerializedName;

public class SFSearchIndexAllocationDetails extends SFODataObject {

    @SerializedName("AccountId")
    private String AccountId;
    @SerializedName("AccountType")
    private String AccountType;
    @SerializedName("Subdomain")
    private String Subdomain;
    @SerializedName("DbName")
    private String DbName;
    @SerializedName("UserCount")
    private Integer UserCount;

    public String getAccountId() {
        return this.AccountId;
    }

    public void setAccountId(String accountid) {
        this.AccountId = accountid;
    }

    public String getAccountType() {
        return this.AccountType;
    }

    public void setAccountType(String accounttype) {
        this.AccountType = accounttype;
    }

    public String getSubdomain() {
        return this.Subdomain;
    }

    public void setSubdomain(String subdomain) {
        this.Subdomain = subdomain;
    }

    public String getDbName() {
        return this.DbName;
    }

    public void setDbName(String dbname) {
        this.DbName = dbname;
    }

    public Integer getUserCount() {
        return this.UserCount;
    }

    public void setUserCount(Integer usercount) {
        this.UserCount = usercount;
    }

}