// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//     
//	   Copyright (c) 2017 Citrix ShareFile. All rights reserved.
// </auto-generated>
// ------------------------------------------------------------------------------

package com.citrix.sharefile.api.models;

import com.google.gson.annotations.SerializedName;

public class SFSecurityQuestion extends SFODataObject {

    @SerializedName("Question")
    private String Question;
    @SerializedName("Answer")
    private String Answer;
    @SerializedName("IsResetRequired")
    private Boolean IsResetRequired;

    public String getQuestion() {
        return this.Question;
    }

    public void setQuestion(String question) {
        this.Question = question;
    }

    public String getAnswer() {
        return this.Answer;
    }

    public void setAnswer(String answer) {
        this.Answer = answer;
    }

    public Boolean getIsResetRequired() {
        return this.IsResetRequired;
    }

    public void setIsResetRequired(Boolean isresetrequired) {
        this.IsResetRequired = isresetrequired;
    }

}