// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//     
//	   Copyright (c) 2017 Citrix ShareFile. All rights reserved.
// </auto-generated>
// ------------------------------------------------------------------------------

package com.citrix.sharefile.api.models;

import com.google.gson.annotations.SerializedName;

public class SFSearchTextFieldSelectorFlags extends SFODataObject {

    @SerializedName("FirstName")
    private Boolean FirstName;
    @SerializedName("LastName")
    private Boolean LastName;
    @SerializedName("Email")
    private Boolean Email;
    @SerializedName("Company")
    private Boolean Company;

    /**
     * FirstName
     */
    public Boolean getFirstName() {
        return this.FirstName;
    }

    /**
     * FirstName
     */
    public void setFirstName(Boolean firstname) {
        this.FirstName = firstname;
    }

    /**
     * LastName
     */
    public Boolean getLastName() {
        return this.LastName;
    }

    /**
     * LastName
     */
    public void setLastName(Boolean lastname) {
        this.LastName = lastname;
    }

    /**
     * Email
     */
    public Boolean getEmail() {
        return this.Email;
    }

    /**
     * Email
     */
    public void setEmail(Boolean email) {
        this.Email = email;
    }

    /**
     * Company
     */
    public Boolean getCompany() {
        return this.Company;
    }

    /**
     * Company
     */
    public void setCompany(Boolean company) {
        this.Company = company;
    }

}