// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//     
//	   Copyright (c) 2017 Citrix ShareFile. All rights reserved.
// </auto-generated>
// ------------------------------------------------------------------------------

package com.citrix.sharefile.api.models;

import com.google.gson.annotations.SerializedName;

public class SFShareSettings extends SFODataObject {

    @SerializedName("NotifyOnUse")
    private Boolean NotifyOnUse;

    /**
     * Notify the creator when Share is used.
     */
    public Boolean getNotifyOnUse() {
        return this.NotifyOnUse;
    }

    /**
     * Notify the creator when Share is used.
     */
    public void setNotifyOnUse(Boolean notifyonuse) {
        this.NotifyOnUse = notifyonuse;
    }

}