// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//     
//	   Copyright (c) 2017 Citrix ShareFile. All rights reserved.
// </auto-generated>
// ------------------------------------------------------------------------------

package com.citrix.sharefile.api.models;

import com.google.gson.annotations.SerializedName;

public class SFShareFileCitrixCloudSession extends SFODataObject {

    @SerializedName("CitrixCloudSession")
    private SFCitrixCloudSession CitrixCloudSession;
    @SerializedName("SFSession")
    private SFSession SFSession;

    /**
     * Cwc Session Info
     */
    public SFCitrixCloudSession getCitrixCloudSession() {
        return this.CitrixCloudSession;
    }

    /**
     * Cwc Session Info
     */
    public void setCitrixCloudSession(SFCitrixCloudSession citrixcloudsession) {
        this.CitrixCloudSession = citrixcloudsession;
    }

    /**
     * Associated ShareFile session
     */
    public SFSession getSFSession() {
        return this.SFSession;
    }

    /**
     * Associated ShareFile session
     */
    public void setSFSession(SFSession sfsession) {
        this.SFSession = sfsession;
    }

}