// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//     
//	   Copyright (c) 2017 Citrix ShareFile. All rights reserved.
// </auto-generated>
// ------------------------------------------------------------------------------

package com.citrix.sharefile.api.models;

import com.google.gson.annotations.SerializedName;

public class SFSSOInfoEntry extends SFODataObject {

    @SerializedName("Key")
    private String Key;
    @SerializedName("Value")
    private String Value;

    /**
     * Key
     */
    public String getKey() {
        return this.Key;
    }

    /**
     * Key
     */
    public void setKey(String key) {
        this.Key = key;
    }

    /**
     * Value
     */
    public String getValue() {
        return this.Value;
    }

    /**
     * Value
     */
    public void setValue(String value) {
        this.Value = value;
    }

}