// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//     
//	   Copyright (c) 2017 Citrix ShareFile. All rights reserved.
// </auto-generated>
// ------------------------------------------------------------------------------

package com.citrix.sharefile.api.models;

import com.google.gson.annotations.SerializedName;

public class SFStorageSettings extends SFODataObject {

    @SerializedName("StorageZoneId")
    private String StorageZoneId;

    public String getStorageZoneId() {
        return this.StorageZoneId;
    }

    public void setStorageZoneId(String storagezoneid) {
        this.StorageZoneId = storagezoneid;
    }

}