// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//     
//	   Copyright (c) 2017 Citrix ShareFile. All rights reserved.
// </auto-generated>
// ------------------------------------------------------------------------------

package com.citrix.sharefile.api.models;

import com.google.gson.annotations.SerializedName;

import java.util.ArrayList;

public class SFStructuredDownloadFolder extends SFStructuredDownloadItem {

    @SerializedName("Children")
    private ArrayList<SFStructuredDownloadItem> Children;
    @SerializedName("Name")
    private String Name;

    public ArrayList<SFStructuredDownloadItem> getChildren() {
        return this.Children;
    }

    public void setChildren(ArrayList<SFStructuredDownloadItem> children) {
        this.Children = children;
    }

    public String getName() {
        return this.Name;
    }

    public void setName(String name) {
        this.Name = name;
    }

}