// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//     
//	   Copyright (c) 2017 Citrix ShareFile. All rights reserved.
// </auto-generated>
// ------------------------------------------------------------------------------

package com.citrix.sharefile.api.models;

import com.google.gson.annotations.SerializedName;

public class SFSupportMethod extends SFODataObject {

    @SerializedName("Order")
    private Integer Order;
    @SerializedName("Name")
    private String Name;
    @SerializedName("Description")
    private String Description;
    @SerializedName("Region")
    private String Region;
    @SerializedName("ShowAlways")
    private Boolean ShowAlways;

    public Integer getOrder() {
        return this.Order;
    }

    public void setOrder(Integer order) {
        this.Order = order;
    }

    public String getName() {
        return this.Name;
    }

    public void setName(String name) {
        this.Name = name;
    }

    public String getDescription() {
        return this.Description;
    }

    public void setDescription(String description) {
        this.Description = description;
    }

    public String getRegion() {
        return this.Region;
    }

    public void setRegion(String region) {
        this.Region = region;
    }

    public Boolean getShowAlways() {
        return this.ShowAlways;
    }

    public void setShowAlways(Boolean showalways) {
        this.ShowAlways = showalways;
    }

}