// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//     
//	   Copyright (c) 2017 Citrix ShareFile. All rights reserved.
// </auto-generated>
// ------------------------------------------------------------------------------

package com.citrix.sharefile.api.models;

import com.google.gson.annotations.SerializedName;

public class SFSubdomainAvailabilityResult extends SFODataObject {

    @SerializedName("IsSubdomainAvailable")
    private Boolean IsSubdomainAvailable;

    /**
     * Indicates if subdomain is available to claim for an account
     */
    public Boolean getIsSubdomainAvailable() {
        return this.IsSubdomainAvailable;
    }

    /**
     * Indicates if subdomain is available to claim for an account
     */
    public void setIsSubdomainAvailable(Boolean issubdomainavailable) {
        this.IsSubdomainAvailable = issubdomainavailable;
    }

}