// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//     
//	   Copyright (c) 2017 Citrix ShareFile. All rights reserved.
// </auto-generated>
// ------------------------------------------------------------------------------

package com.citrix.sharefile.api.models;

import com.google.gson.annotations.SerializedName;

import java.util.Map;

public class SFTenantZoneUsageReport extends SFODataObject {

    @SerializedName("TenantsToZones")
    private Map<String, SFZoneUsageBreakdown> TenantsToZones;

    public Map<String, SFZoneUsageBreakdown> getTenantsToZones() {
        return this.TenantsToZones;
    }

    public void setTenantsToZones(Map<String, SFZoneUsageBreakdown> tenantstozones) {
        this.TenantsToZones = tenantstozones;
    }

}