// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//     
//	   Copyright (c) 2017 Citrix ShareFile. All rights reserved.
// </auto-generated>
// ------------------------------------------------------------------------------

package com.citrix.sharefile.api.models;

import com.google.gson.annotations.SerializedName;

public class SFToolInformation extends SFODataObject {

    @SerializedName("ToolName")
    private String ToolName;
    @SerializedName("Version")
    private String Version;

    /**
     * Tool Name
     */
    public String getToolName() {
        return this.ToolName;
    }

    /**
     * Tool Name
     */
    public void setToolName(String toolname) {
        this.ToolName = toolname;
    }

    /**
     * Tool Version
     */
    public String getVersion() {
        return this.Version;
    }

    /**
     * Tool Version
     */
    public void setVersion(String version) {
        this.Version = version;
    }

}