// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//     
//	   Copyright (c) 2017 Citrix ShareFile. All rights reserved.
// </auto-generated>
// ------------------------------------------------------------------------------

package com.citrix.sharefile.api.models;

import com.google.gson.annotations.SerializedName;

import java.util.ArrayList;

public class SFUserBulkOperationRequest extends SFODataObject {

    @SerializedName("UserIds")
    private ArrayList<String> UserIds;

    /**
     * List of user ids to perform this operation on
     */
    public ArrayList<String> getUserIds() {
        return this.UserIds;
    }

    /**
     * List of user ids to perform this operation on
     */
    public void setUserIds(ArrayList<String> userids) {
        this.UserIds = userids;
    }

}