// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//     
//	   Copyright (c) 2017 Citrix ShareFile. All rights reserved.
// </auto-generated>
// ------------------------------------------------------------------------------

package com.citrix.sharefile.api.models;

import com.google.gson.annotations.SerializedName;

public class SFUserPolicy extends SFODataObject {

    @SerializedName("UserId")
    private String UserId;
    @SerializedName("Active")
    private Boolean Active;
    @SerializedName("Policy")
    private SFPolicy Policy;

    /**
     * User Identifier
     */
    public String getUserId() {
        return this.UserId;
    }

    /**
     * User Identifier
     */
    public void setUserId(String userid) {
        this.UserId = userid;
    }

    /**
     * Flag to indicate if this Policy is turned on for this User
     */
    public Boolean getActive() {
        return this.Active;
    }

    /**
     * Flag to indicate if this Policy is turned on for this User
     */
    public void setActive(Boolean active) {
        this.Active = active;
    }

    /**
     * The Policy assigned
     */
    public SFPolicy getPolicy() {
        return this.Policy;
    }

    /**
     * The Policy assigned
     */
    public void setPolicy(SFPolicy policy) {
        this.Policy = policy;
    }

}