// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//     
//	   Copyright (c) 2017 Citrix ShareFile. All rights reserved.
// </auto-generated>
// ------------------------------------------------------------------------------

package com.citrix.sharefile.api.models;

import com.google.gson.annotations.SerializedName;

import java.util.ArrayList;

public class SFWebhookSupportedContext extends SFODataObject {

    @SerializedName("ResourceType")
    private String ResourceType;
    @SerializedName("Events")
    private ArrayList<SFWebhookSupportedEvents> Events;

    public String getResourceType() {
        return this.ResourceType;
    }

    public void setResourceType(String resourcetype) {
        this.ResourceType = resourcetype;
    }

    public ArrayList<SFWebhookSupportedEvents> getEvents() {
        return this.Events;
    }

    public void setEvents(ArrayList<SFWebhookSupportedEvents> events) {
        this.Events = events;
    }

}