// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//     
//	   Copyright (c) 2017 Citrix ShareFile. All rights reserved.
// </auto-generated>
// ------------------------------------------------------------------------------

package com.citrix.sharefile.api.models;

import com.google.gson.annotations.SerializedName;

public class SFWebhookSupportedEvents extends SFODataObject {

    @SerializedName("ResourceType")
    private String ResourceType;
    @SerializedName("OperationName")
    private String OperationName;

    public String getResourceType() {
        return this.ResourceType;
    }

    public void setResourceType(String resourcetype) {
        this.ResourceType = resourcetype;
    }

    public String getOperationName() {
        return this.OperationName;
    }

    public void setOperationName(String operationname) {
        this.OperationName = operationname;
    }

}